**Docteur Pierre Brasseur : Sociologue & Professeur à l'Université Libre
de Bruxelles**

### Domaines d'expertise :

-   Genre et sexualité

-   Handicap et société

-   Méthodologies de recherche en sciences sociales

-   Inégalités sociales

-   Travail sexuel en ligne

### Parcours académique :

-   **Professeur** à l'Université Libre de Bruxelles

-   **Postdoctorats** à l'INSERM et à l'Université de Grenoble

### Recherche et enseignement :

Dr. Brasseur mène des recherches innovantes sur les intersections entre
genre, sexualité et handicap. Il explore notamment :

-   La sexualité des personnes en situation de handicap

-   Les dynamiques du travail sexuel en ligne

-   L'impact des catégories sociales sur les trajectoires
    professionnelles

En tant qu'enseignant passionné, il guide ses étudiants dans la
recherche en sciences sociales, les encourageant à développer une pensée
critique et des méthodologies rigoureuses.

### Publications et conférences :

Auteur prolifique, Dr. Brasseur contribue régulièrement à des revues
scientifiques et participe à des conférences internationales. Ses
travaux éclairent les dynamiques de pouvoir liées au genre et au
handicap dans notre société.

### **Postes précédents** :

-   Postdoctorant au SESSTIM Marseille et au Cermes3, UMR 8211
    (recherche sur les essais cliniques).

-   Postdoctorant à Arènes, EHESP, CNRS (étude sur la santé mentale dans
    la fonction publique environnementale).

-   Président du jury de l’épreuve écrite de sociologie à l’ENS
    Paris-Saclay (depuis 2022).

### **Domaines d'enseignement** :

-   Sociologie de la santé

-   Sociologie du genre

-   Sociologie du handicap

-   Politiques sociales

### **Formation** :

-   **Doctorat en sociologie**, Université de Lille (2017), thèse :
    *"L’invention de l’assistance sexuelle : sociohistoire d’un problème
    public français"*.

-   **Master 2 en sociologie**, Université Lille 1 (2011).

-   **Master 1 en sociologie**, Université Lille 1 (2010).

-   **Licence en sociologie**, Université Lille 1 (2009).

### **Expériences postdoctorales** :

-   **INSERM** (2021) – Étude des tentatives de suicide pendant la
    pandémie de COVID-19.

-   **IRDES Paris** (2019) – Analyse des inégalités sociales d’accès à
    l’emploi et aux aides techniques.

-   **Université de Lille** (2019) – Recherche sur les inégalités
    sociales de santé.

-   **Université de Grenoble** (2017-2020) – Étude du travail sur les
    plateformes numériques.

### **Engagements scientifiques** :

-   Responsable du Groupe éthique professionnelle et Lutte contre les
    violences sexistes et sexuelles à l'Association Française de
    Sociologie (2020).

-   Responsable du Réseau Thématique "Recherches en sciences sociales
    sur la sexualité" à l'AFS (2017).

-   Membre élu du Bureau restreint de l’Association Française de
    Sociologie (2017).

-   Responsable du Groupe Thématique "Sociologie du handicap" à l’AISLF
    (2021).

### **Membre de laboratoires** :

-   Membre du laboratoire Pacte, Sciences Po Grenoble, Université
    Grenoble Alpes (depuis 2017).
