---
title: "Pierre Brasseur | Sociologue"
---

# Chargé de Cours et Professeur à l'Université Libre de Bruxelles

## Coordonnées

**Campus de Charleroi** Zénobe Gramme - Entrée rue Lebeau 31, blvd
Solvay 6000 Charleroi

**Campus du Solbosch Bruxelles (Bât.S)** 13e étage - Bureau S13.129
Avenue Jeanne 44 (CP 124) 1050 Bruxelles

**Email:** [pierre.brasseur\@ulb.be](mailto:pierre.brasseur@ulb.be)

# Biographie

Pierre Brasseur est chercheur au Centre METICES et professeur à
l'Université Libre de Bruxelles (ULB) depuis septembre 2024. Ses
domaines d'expertise incluent :

-   Sexualité et genre

-   Handicap

-   Santé

-   Monde du travail

-   Sciences sociales de l'enfance

-   Violence sexiste et sexuelle dans le sport

Avant de rejoindre l'ULB, il a occupé des postes de direction au sein de
l'Association française de sociologie.

# Enseignements (ULB, Charleroi et Bruxelles)

-   [Théorie du travail
    social](https://www.ulb.be/fr/programme/soca-d495-1)

-   [Mobilisations, genre et identités
    professionnelles](https://www.ulb.be/fr/programme/soca-d554-1)

-   [Méthodes de recherche en sciences
    humaines](https://www.ulb.be/fr/programme/soca-d400-1)

-   Care au travail : famille, santé (à partir de 2024)

# Axes de recherche

-   Sexualité au travail

-   Orientation sexuelle comme variable scientifique

-   Travail dans les lieux d'enfermement

-   Éducation à la sexualité et à l'égalité des sexes

-   Sciences de l'enfance

-   Méthodes de recherche en terrains sensibles

## Encadrement d'étudiants

Pierre Brasseur supervise des mémoires et thèses en sociologie sur des
thèmes tels que le handicap, la santé, la sexualité, le travail
domestique et les questions LGBT.

**Pour proposer un projet:** Envoyez votre CV et un projet de recherche
(2 pages max) à [pierre.brasseur\@ulb.be](mailto:pierre.brasseur@ulb.be)

# Publications sélectionnées

## Livre

-   "Sociologie de l'assistance sexuelle : Former et transformer la
    sexualité" (PUF, 2023)

## Articles récents

-   "Comment peut-on dire la sexualité ?" (2022)

-   "L'espace contemporain de la formation en sociologie en France"

    (2021) 

-   "Les économies de la sexualité" (2020)

[Liste complète des
publications](https://lex.page/d/lien-vers-page-publications)

# Profils académiques

-   [Google
    Scholar](https://scholar.google.fr/citations?user=O4AvHvkAAAAJ&hl=fr)

-   [ResearchGate](https://www.researchgate.net/profile/Pierre-Brasseur-3)

# Domaines d'intérêt

Santé \| Numérique \| Sexualité \| Enfance \| Pornographie \| Travail \|
Handicap \| Émotion \| Éthique de la Recherche

### **Langues et outils**

-   **Langues** :

    -   Français (langue maternelle)

    -   Anglais (lu, écrit, parlé)

    -   Espagnol (lu, parlé)

-   **Compétences méthodologiques** :

    -   Conduite d'entretiens (récits de vie, informatifs,
        semi-directifs) : environ 300 entretiens réalisés.

    -   Recherche, traitement et exploitation de sources documentaires
        et d'archives.

    -   Observation participante, éthique de la recherche, droit des
        enquêtés et de l’enquêteur.

    -   Ethnographie d’internet.

    -   Méthodes comparatives internationales.

    -   Méthodes qualitatives et enquêtes mixtes.

    -   Techniques d’analyse des réseaux, questionnaires (LimeSurvey).

    -   Exploitation de bases de données secondaires.

-   **Outils informatiques** :

    -   Microsoft Office, Zotero, Endnote, LimeSurvey, Pajek, WordPress,
        SAS.

## **Activité éditoriale**

-   **Depuis 2022** : Membre du comité de rédaction de la revue
    *Tracés*.

-   **Depuis 2015** : Membre du comité de rédaction de la revue
    *Socio-logos*.

-   **2015-2020** : Rédacteur en chef de la revue *Socio-logos*.

### **Activités d’évaluation**

-   **Évaluation d'articles et de livres** pour les revues et éditeurs
    suivants :

    -   *Genre, sexualité et société*

    -   *Le Journal des anthropologues*

    -   *Socio-logos*

    -   *Disability and Society*

    -   *Revue française de socioéconomie*

    -   *L’Harmattan*

    -   *Les Carnets de la consommation*

    -   *Questions d’économies de la santé*

    -   *Tracés - Revues de sciences sociales*

    -   *Travail et emploi*

    -   *L’Homme et la société*

    -   *Revue d’économie régionale et urbaine*

    -   *Santé publique*

    -   *Actes de la recherche en sciences sociales*

    -   *Terrains & Travaux*

    -   *Revue française des affaires sociales*

-   **Évaluation de projets de recherche** :

    -   IRESP (4 projets)

    -   Thèse CIFRE (1 projet)

    -   Open-Editions (1 projet)

-   **Rédacteur** pour la Haute Autorité de Santé : analyse et rédaction
    de rapports, notamment sur l'habitat et l'inclusion.

## **Direction de mémoires et participation à des jurys**

-   **Direction de mémoires** :

    -   *Tiffany Bailliez* : *La santé sexuelle des femmes aveugles*,
        École des sages-femmes de Tours, 2017.

    -   *Léa Pons* : *Couple et EHPAD*, Master 1, Université de
        Grenoble, 2022.

    -   *Carine Pignard* : *Solitude et vieillesse*, Master 1,
        Université de Grenoble, 2022.

    -   *Mathilde Ferrary* : *L’autisme comme problème public*, Master
        2, Sciences Po Grenoble, 2022.

-   **Membre de jury de thèse** :

    -   *Noémie Rimbourg* : *L’autonomie à l’épreuve du handicap*,
        Université Saint-Louis Bruxelles.

-   **Autres activités** :

    -   Enquêteur pour l’IRDES (2019-2023).

    -   Participation à des jurys pour des mémoires et thèses.
