---
title: "Recherches"
---

# Axes de recherche

Mon travail se concentre sur l'intersection de la sociologie, la santé
publique et les politiques sociales. Mes principaux domaines d'expertise
incluent :

-   Handicap et inclusion

-   Sexualité et santé sexuelle

-   Santé mentale

-   Politiques publiques et leur mise en œuvre

-   Économie du care et du travail intime

-   Sociologie des problèmes publics

## Parcours et approche

Mon parcours de recherche est guidé par une passion pour comprendre les
enjeux sociétaux liés à la santé, au handicap et à la sexualité.
J'examine en particulier :

-   Les diverses formes de mobilisation citoyenne autour de ces
    questions

-   La marchandisation croissante de certains aspects du care et de
    l'intime

-   Le rôle des professionnels dans l'application des politiques
    publiques

-   L'évolution de la prise en charge étatique de ces problématiques

## Projets de recherche actuels

-   **Projet IPACOS** : Étude sociologique des suicides pendant la
    pandémie de COVID-19

-   Inégalités sociales dans la santé et la sexualité :

    -   [Travailleurs du sexe en ligne : dynamiques de marché et santé
        sexuelle](pierrebrassseur.fr/recherches/ecosex.qmd)

    -   Impact du COVID-19 sur les comportements suicidaires

    -   Handicap, emploi et accès aux aides techniques

    -   Santé sexuelle chez les jeunes

-   Inégalités sociales dans la maladie

-   Le handicap comme prisme pour comprendre le genre et la sexualité
