project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - href: about.qmd
        text: Blog de Pierre Brasseur
      - href: pierrebrasseur.fr
        text: Accueil
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

