---
title: "Publications"
---

# **Ouvrages :**

Pierre Brasseur (2024), *Sociologie de l'assistance sexuelle : former et
transformer la sexualité*, Presses Universitaires de France. ISBN:
978-2-13-084229-3

# **Articles dans des revues :**

Florian Vörös (2023), *Désirer comme un homme. Enquête sur les fantasmes
et la masculinité*, revue *Réseaux*, 237 (1), pp. 265-268. DOI :
10.3917/res.237.0265

Ward Jane (2023), *The Tragedy of Heterosexuality*, revue *Revue
Française de Science Politique*, Chronique bibliographique Genre, 72
(5), pp. 822-823. DOI : 10.3917/rfsp.725.0822

Pierre Brasseur (2022), *Ne plus pouvoir aimer : le récit de Tristan
"vieux, Pd, handicapé"*, revue *Sicurezza e scienze sociali*, pp. 35-66.
DOI : 10.3280/siss2021-003003

Pierre Brasseur, Cécile Thomé & Milena Jakšić (2022), *Comment peut-on
dire la sexualité ?*, revue *Terrains et Travaux*, Dire la sexualité, 40
(1), pp. 5-19. DOI : 10.3917/tt.040.0005

Pierre Bataille & Pierre Brasseur (2021), *L’espace contemporain de la
formation en sociologie en France*, revue *Socio-logos*, Formation :
sociologue, 15. DOI : 10.4000/socio-logos.5203

Jean Finez & Pierre Brasseur (2020), *Les économies de la sexualité*,
revue *Revue Française de Socio-Economie*, 25, pp. 15-28. DOI :
10.3917/rfse.025.0015

Pierre Brasseur & Lucie Nayak (2018), *Handicap, genre et sexualité :
actualités de la recherche francophone*, revue *Genre, sexualité &
société*, 19. DOI : 10.4000/gss.4362

Pierre Brasseur (2016), *De la mixité au droit : sexualité et intimité
dans les institutions accueillant malades et personnes handicapées
depuis les années 1970*, revue *Sexologies*, 25 (3), pp. 107-113. DOI :
10.1016/j.sexol.2016.05.006

Pierre Brasseur (2015), *Des sexualités et des handicaps : Questions
d’intimités*, revue *Alter: European Journal of Disability Research*, 9
(4), pp. 373-376. DOI : 10.1016/j.alter.2015.07.003

Pierre Brasseur & Geneviève Cresson (2015), *Eva Illouz Pourquoi l’amour
fait mal. L’expérience amoureuse dans la modernité*, revue *Revue
Française de Sociologie*, pp. 165-168. DOI : 10.3917/rfs.561.0165

Pierre Brasseur & Pauline Detuncq (2014), *L’assistance sexuelle :
qu’est-ce-à-dire ? Quels enjeux ?*, revue *VST - Vie sociale et
traitements*, N° 123 (3), pp. 51-56. DOI : 10.3917/vst.123.0051

Pierre Brasseur (2014), *Fausto-Sterling Anne, Corps en tous genres. La
dualité des sexes à l’épreuve de la science*, revue *Genre, sexualité &
société*, 11 (4), pp. 433. DOI : 10.4000/gss.3184

Pierre Brasseur (2014), *Kafer Alisson. Feminist, queer, crip*, revue
*Alter: European Journal of Disability Research*, 8 (4), pp. 298-300.
DOI : 10.1016/j.alter.2014.09.008

Pierre Brasseur (2012), *Mathieu Trachman, Le travail pornographique*,
revue *Lectures*. DOI : 10.4000/lectures.11591

Pierre Brasseur (2012), *Catherine Bouve, Catherine Sellenet, Confier
son enfant. L’univers des assistantes maternelles*, revue *Lectures*.
DOI : 10.4000/lectures.7343

Pierre Brasseur (2010), *Claire Merlin, Sourde en centres d'appels.
Plaidoyer pour une Distanciation Intégrante envers les personnes en
situation de handicap*, revue *Lectures*. DOI : 10.4000/lectures.1325

### **Chapitres d'ouvrages :**

Pierre Brasseur (2023), *Les assistantes sexuelles, des travailleuses du
sexe ?*, in *Work3 : Travail domestique, travail professionnel, travail
politique*, Presses Universitaires de Nanterre, pp. 91-100. DOI :
10.3917/parti.022.0139

Pierre Brasseur (2018), *Handicap et sexualité : une approche
sociologique*, in *Sexualités, autonomie et handicaps : freins et
perspectives*, LEH Édition

Pierre Brasseur (2017), *Le sexe politique du handicap*, in *Handicap et
sexualité*, L’Harmattan

Pierre Brasseur (2016), *La sexualité des personnes en situation de
handicap comme problème public et politique*, in *Les politiques de la
sexualité : avancées et résistances*, L’Harmattan

Pierre Brasseur (2016), *Sociologie des relations entre handicap et
travail du sexe*, in *Genre, travail du sexe et santé sexuelle*,
Association Grisélidis

Pierre Brasseur (2016), *Handicap*, in *Encyclopédie critique du genre*,
La Découverte. DOI : 10.3917/dec.renne.2016.01.0293

### **Communications dans des congrès :**

Pierre Brasseur (2024), *Ces LGBT qui ne font rien : le travail
sous-estimé des drag queens*, Journées internationales de sociologie du
travail, Evry, France. halshs-04633839v1

Pierre Brasseur (2024), *Réexamen des hypothèses sur les différences
entre homosexuels et hétérosexuels dans la recherche contemporaine*,
Congrès international des sociologues de langue française, AISLF,
Ottawa, Canada. halshs-04633834v1

Pierre Brasseur (2023), *Le corps, c’est lui, l’esprit, c’est elle*,
Séminaire *Genre et Gynécologie : savoirs, pratiques & mobilisations*,
Aubervilliers, France. halshs-04070794v1

Pierre Brasseur (2023), *Le handicap n’est pas une variable*, Séminaire
*Genre et inégalité sociale de santé*, Université Catholique de Lille.
halshs-03833609v1

Pierre Brasseur (2021), *Les handicapés témoins, les valides experts :
mobilisations en faveur du droit à la sexualité*, revue
*Participations*, 22 (3), pp. 139-158. DOI : 10.3917/parti.022.0139
